### ISSUE TITLE
Error after adding inversify in project node_modules/inversify/lib/annotation/injectable.d.ts

### ISSUE THREAD

**Issue by AdieOlami** [remojansen/InversifyJS#1442]
## Expected Behavior

To run yarn watch and have no error

## Current Behavior

`node_modules/inversify/lib/annotation/injectable.d.ts:1:52 - error TS1005: ',' expected.

1 declare function injectable(): <T extends abstract new (...args: never) => unknown>(target: T) => T;
                                                     ~~~

node_modules/inversify/lib/annotation/injectable.d.ts:1:83 - error TS1144: '{' or ';' expected.

1 declare function injectable(): <T extends abstract new (...args: never) => unknown>(target: T) => T;
                                                                                    ~

node_modules/inversify/lib/annotation/injectable.d.ts:1:91 - error TS1005: ')' expected.

1 declare function injectable(): <T extends abstract new (...args: never) => unknown>(target: T) => T;
                                                                                            ~

node_modules/inversify/lib/annotation/injectable.d.ts:1:94 - error TS1005: ';' expected.

1 declare function injectable(): <T extends abstract new (...args: never) => unknown>(target: T) => T;
                                                                                               ~

node_modules/inversify/lib/annotation/injectable.d.ts:1:96 - error TS1128: Declaration or statement expected.

1 declare function injectable(): <T extends abstract new (...args: never) => unknown>(target: T) => T;`

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1. yarn add inversify inversify-express-utils reflect-metadata
2.
3.
4.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used: 6.0.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node -v v14.17.0
* Operating System and version (desktop or mobile): Mac
* Link to your project:

# Stack trace
<!--- Include stack trace -->

**Comment by rafal-dudzik-ttpsc** [comment]
I've had similar issue with typescript 4.3.5 globally installed. After upgrading to 4.4.4 everything went fine.

**Comment by anna-sala07** [comment]
Hello [AdieOlami](https://github.com/AdieOlami) I am having the exact same issue and I have typescript Version 4.6.3 installed globally. Node v16.14.2. Did you find a solution for this?

**Comment by shuvo009** [comment]
@anna-sala07 I am having the exact same issue. my global typescript Version was 4.6.3 but my local one is 3.9.4.  After upgrading local one to  4.6.3 everything went fine.

**Comment by yog27ray** [comment]
I am also facing the same issue. I don't have a global installation of typescript but the local one is typescript is 4.1.5.

**Comment by anna-sala07** [comment]
Thank you @shuvo009 ! For some reason my Typescript local was not upgrading when I told it to use the latest version. once my local version was upgraded it started working fine

**Comment by PodaruDragos** [comment]
Hello guys, this had been answered before. The only solution to fix this problem is to update `typescript` to at least `4.4.4`, as the fact that `inversify` itself is running on a `typescript` > `4.4.4`. There is always the possibility of downgrading `inversify` to before `v6`

**Comment by notaphplover** [comment]
Closing the issue. It seems to be a `tsc` issue and no minimum reproduction code is provided.
